### ISSUE TITLE
[Bug]: No PR for pgAdmin v6.21

### ISSUE THREAD

**Issue by dpprdan** [vedantmgoyal9/winget-pkgs-automation#1069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

pgAdmin v6.21 [was released 5 days ago](https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v6.21/windows/) and apparently not picked up yet by winget-pkgs-automation.

v6.20 PR https://github.com/microsoft/winget-pkgs/pull/96603

pgAdmin PRs https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+pgadmin

https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/p/postgresql.pgadmin.json

I failed to find something directly relevant in the Actions logs, but may have missed something. Is there a quick way to search for it?

**Comment by vedantmgoyal2009** [comment]
* https://github.com/pgadmin-org/pgadmin4/issues/5949

**Comment by vedantmgoyal9** [comment]
https://github.com/pgadmin-org/pgadmin4/tags

It is published on the website, but not on the GitHub repository, which is why the automation was not able to find the v6.21 release. I have created an issue.
* https://github.com/pgadmin-org/pgadmin4/issues/5949

**Comment by dpprdan** [comment]
[fixed](https://github.com/microsoft/winget-pkgs/pull/99556), thanks!
