### ISSUE TITLE
OctopusDeploy Automation

### ISSUE THREAD

**Issue by droyad** [vedantmgoyal9/winget-pkgs-automation#1133]
### What would you like to see changed/added?

Hi, I work for Octopus Deploy and was looking into how our application gets up to WinGet, as we are interested in doing it ourselves. The search lead me here, so thank you for publishing it for us.

Co-incidentally it looks like the automation was removed yesterday. Did it move somewhere else?

**Comment by vedantmgoyal9** [comment]
Hi, you can publish of OctopusDeploy by integrating Microsoft's WinGet-Create in CI/CD pipelines.

For Octopus Server:

```
wingetcreate update OctopusDeploy.Server -v 2023.1.9791 -u https://download.octopusdeploy.com/octopus/Octopus.2023.1.9791-x64.msi -t <GITHUB_PAT> --submit
```

For Octopus Tentacle:

```
wingetcreate update OctopusDeploy.Tentacle -v 6.3.417 -u https://download.octopusdeploy.com/octopus/Octopus.Tentacle.6.3.417-x64.msi https://download.octopusdeploy.com/octopus/Octopus.Tentacle.6.3.417.msi -t <GITHUB_PAT> --submit
```

Documentation for `update` command: https://github.com/microsoft/winget-create/blob/main/doc/update.md

Documentation for integrating into CI/CD pipelines: https://github.com/microsoft/winget-create#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline

Example of a GitHub workflow which uses WinGet Releaser: https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml

---

Edit: Automation is now back in this repository only :)

**Comment by vedantmgoyal2009** [comment]
@droyad hello?

**Comment by vedantmgoyal9** [comment]
@droyad hello?

**Comment by droyad** [comment]
@vedantmgoyal2009 Thanks for the info. At the moment we're still looking into whether we are going to official support for WinGet, so thank you for your efforts.
