### ISSUE TITLE
[New Package]: Mythicsoft.AgentRansack

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#1188]
### List the PackageIdentifier of the package to be added to automation

Mythicsoft.AgentRansack

### Details about the application

PackageVersion, ReleaseNotes:
https://www.mythicsoft.com/getversion.aspx?productid=1&infotype=1

InstallerUrl: Concat string or parse https://www.mythicsoft.com/agentransack/

PR: https://github.com/microsoft/winget-pkgs/pull/82666

**Comment by vedantmgoyal9** [comment]
https://www.mythicsoft.com/getversion.aspx?productid=1&infotype=1

I can't find PackageVersion in it.

**Comment by vedantmgoyal9** [comment]
@SpecterShell I can't find PackageVersion in it.
https://www.mythicsoft.com/getversion.aspx?productid=1&infotype=1
