### ISSUE TITLE
[New Package]: AdGuard.AdGuard

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#1189]
### List the PackageIdentifier of the package to be added to automation

AdGuard.AdGuard

### Details about the application

PR: https://github.com/microsoft/winget-pkgs/pull/82500

**Comment by vedantmgoyal9** [comment]
API returns 7.10.3961.0, whereas https://adguard.com/en/versions/windows/release.html says 7.10.2.

**Comment by SpecterShell** [comment]
If you install from their website (<https://download.adguard.com/d/24276/adguardInstaller.exe>, which downloads <http://static.adtidy.org/windows/setup.exe>) you will still get 7.10.3961.0. And either 7.10.3961 or 7.10.3 is greater than 7.10.2.

**Comment by SpecterShell** [comment]
BTW https://github.com/AdguardTeam/AdguardForWindows/

**Comment by vedantmgoyal9** [comment]
You can add Beta and Nightly packages to WinGet, and then I'll make an issue for winget-releaser.

**Comment by vedantmgoyal9** [comment]
Well there's one already and I've commented on it:

* https://github.com/AdguardTeam/AdguardForWindows/issues/3325

**Comment by SpecterShell** [comment]
The latest version from their repo's releases is updated by major version, while the one from the upgrade API is updated by minor version, which means the former one may sometimes lag behind, at least for now.

**Comment by vedantmgoyal9** [comment]
> If you install from their website (https://download.adguard.com/d/24276/adguardInstaller.exe, which downloads http://static.adtidy.org/windows/setup.exe) you will still get 7.10.3961.0. And either 7.10.3961 or 7.10.3 is greater than 7.10.2.

@SpecterShell the API seems to be on track now. So, can you please revert your comment to include the original API link back?

**Comment by vedantmgoyal9** [comment]
https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/a/adguard.adguard.json
