### ISSUE TITLE
[Feature/Idea]: I saw you updated GnuCash 5.0 for winget

### ISSUE THREAD

**Issue by kamanwu** [vedantmgoyal9/winget-pkgs-automation#1202]
### What would you like to see changed/added?

Now, GnuCash 5.1 is out.  Do you have time to update it as well?  Thanks.

**Comment by vedantmgoyal9** [comment]
I'm refactoring automation a bit. It will be done shortly once I push the fixes.

**Comment by vedantmgoyal9** [comment]
Automation is live now. It will get updated in the next runs.
