### ISSUE TITLE
youdao.youdaodict changed its name in latest version

### ISSUE THREAD

**Issue by lychichem** [vedantmgoyal9/winget-pkgs-automation#1227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In version 10.0.0.0, youdao.youdaodict changed its name to youdao translate and ARP info changed to 网易有道翻译. How should we deal with old versions and latest version?

**Comment by lychichem** [comment]
See https://fanyi.youdao.com/download-release-notes for details

**Comment by vedantmgoyal9** [comment]
@lychichem You opened and closed this issue. Before I close the issue from my side, can you please tell if there's still anything that is to be changed in the JSON here, at this repo?

https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/y/youdao.youdaodict.json

**Comment by lychichem** [comment]
> @lychichem You opened and closed this issue. Before I close the issue from my side, can you please tell if there's still anything that is to be changed in the JSON here, at this repo?
> 
> https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/y/youdao.youdaodict.json

I found a good way to deal with it (at least for now). Maybe start from September we can change id to youdao.youdaotranslate, because we have gave enough time for users to upgrade.
