### ISSUE TITLE
[Bug]: KDE.Kate wrong download URL

### ISSUE THREAD

**Issue by o-l-a-v** [vedantmgoyal9/winget-pkgs-automation#1288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Project Name

WinGet Automation

### What happened?

Latest release of KDE.Kate has a non working download URL in the winget-pkgs manifest

https://github.com/microsoft/winget-pkgs/tree/master/manifests/k/KDE/Kate/23.04.3

<img width="976" alt="image" src="https://github.com/vedantmgoyal2009/vedantmgoyal2009/assets/6450056/c2fb0c49-d2df-4dc1-b68d-5fd43e9d127d">

**Comment by vedantmgoyal9** [comment]
* Updated in: https://github.com/microsoft/winget-pkgs/pull/115670
