### ISSUE TITLE
[Bug]: Unintended Description Formatting

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#1315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Project Name

WinGet Automation

### What happened?

I'm not sure if this is an issue from WinGet Automation or Komac, but one of them is splitting every sentence into new lines in the `Description` field of the manifest, ending up too many paragraphs.

For example:
https://github.com/microsoft/winget-pkgs/pull/116460/files#diff-8daa0413cffc563ee1bbd60ecfd15bf0906bbc9812d97aec069331b01de795d5R17-R23
There were only 4 paragraphs in the description field, but now there are 7.

**Comment by vedantmgoyal9** [comment]
It's a Komac bug @russellbanks

**Comment by russellbanks** [comment]
This is intentional for description formatting to avoid really long lines with multiple sentences. Each sentence is put on a new line to make it more readable and formatted.

If you don't want it, I could add a toggle to Komac for this behaviour?

**Comment by vedantmgoyal9** [comment]
@SpecterShell

**Comment by SpecterShell** [comment]
Sorry for late reply. I prefer not as it could break the structure of the text, especially for those with cascading lists such as the one in `Redisant.RabbitMQAssistant`. 🤔

What do you mean by "making it more readable and formatted"? It may look good in terminal but strange in GUI or webpage (if exist). 🤔

BTW Does it also affect ReleaseNotes? In [this PR](https://github.com/microsoft/winget-pkgs/pull/117059/files) part of the text disappeared after "updating".

**Comment by vedantmgoyal9** [comment]
> BTW Does it also affect ReleaseNotes? In [this PR](https://github.com/microsoft/winget-pkgs/pull/117059/files) part of the text disappeared after "updating".

I think the release notes formatter has missed that part. Rest everything is fine, I guess. 

/cc @russellbanks

**Comment by SpecterShell** [comment]
Another example for ReleaseNotes from <https://github.com/microsoft/winget-pkgs/pull/115107>, where some whitespaces were replaced by another character.

![image](https://github.com/vedantmgoyal2009/vedantmgoyal2009/assets/56779163/7a98fbad-16c0-4814-99d2-9f93856b8d09)

Other examples:
https://github.com/microsoft/winget-pkgs/pull/115665/files
https://github.com/microsoft/winget-pkgs/pull/113559/files

**Comment by vedantmgoyal2009** [comment]
@russellbanks
