### ISSUE TITLE
[Bug]: Incorrect InstallerUrls for paint.net

### ISSUE THREAD

**Issue by mdanish-kh** [vedantmgoyal9/winget-pkgs-automation#1333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Project Name

WinGet Automation

### What happened?

The automation produces incorrect Urls for paint.net manifest. [WiX and Portable Urls](https://github.com/microsoft/winget-pkgs/blob/be851349a154acb14af6275812d79b70fadb9ddf/manifests/d/dotPDNLLC/paintdotnet/5.0.9/dotPDNLLC.paintdotnet.installer.yaml#L41-L55) are not replaced correctly in the update. See https://github.com/microsoft/winget-pkgs/issues/117418 and https://github.com/microsoft/winget-pkgs/pull/117419/files

**Comment by vedantmgoyal9** [comment]
* https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/1395

**Comment by DeusMaximus** [comment]
Issue still not fixed. paint.net InstallerURLs for MSI and Portable versions (x64 and arm64) are pointing to the wrong zip.

Here's the PR fixing the last manifest uploaded to microsoft/winget-pkgs: https://github.com/microsoft/winget-pkgs/pull/126924
