### ISSUE TITLE
[Feature/Idea]: Skip generating manifest if relating PR exists

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#1336]
### Project Name

WinGet Automation

### What would you like to see changed/added?

Is there a way to let the automation skip generating manifest and just change the version in the config file if there is already a relating PR for this change, ~~so it won't override my commits~~?

**Comment by vedantmgoyal9** [comment]
That will be very difficult, I guess. Instead, I can set up some notifications/e-mails or any other way which you would prefer, when a PR for a package, which you manage, is opened. The list of packages will be stored in a `SpecterShell.json` file in this repository. Also, I will add you as a collaborator on my fork, so you can directly push changes to my PR.

**Comment by SpecterShell** [comment]
Adding me as a collaborator is enough. 🙂

**Comment by vedantmgoyal9** [comment]
Done :)
