### ISSUE TITLE
[Bug]: Installer architecture is incorrectly changed to x86

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#1395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Project Name

WinGet Automation

### What happened?

[microsoft/winget-pkgs@`20962c3` (#120298)](https://github.com/microsoft/winget-pkgs/pull/120298/commits/20962c3dd1e9e4beb18397b3092538116eba312a)
[microsoft/winget-pkgs@`961b8f5` (#120406)](https://github.com/microsoft/winget-pkgs/pull/120406/commits/961b8f5b122e48842c82455daecfa89774a0459b)
[microsoft/winget-pkgs@`dc7ccee` (#120407)](https://github.com/microsoft/winget-pkgs/pull/120407/commits/dc7ccee5f40386353c6282b17168e1303ca8083c)
https://github.com/microsoft/winget-pkgs/pull/120415/files

**Comment by vedantmgoyal2009** [comment]
@russellbanks please add cases for the reported packages...
