### ISSUE TITLE
[Modify Package]: syndicode.iNFektNFOViewer -> syndicode.iNFekt

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal9/winget-pkgs-automation#1401]
### List the PackageIdentifier of the package to be added to automation

syndicode.iNFekt

### Details about the application

Rename the package in the automation https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/s/syndicode.infektnfoviewer.json to `syndicode.iNFekt`.

- https://github.com/microsoft/winget-pkgs/pull/120639

**Comment by vedantmgoyal9** [comment]
* Resolved in https://github.com/vedantmgoyal2009/vedantmgoyal2009/commit/293eeff044e3bcee54dd782b2b77fcf852eaa01c
