### ISSUE TITLE
[Bug]: Paint.net broken InstallerURL

### ISSUE THREAD

**Issue by lychichem** [vedantmgoyal9/winget-pkgs-automation#1411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Project Name

WinGet Automation

### What happened?

Automation should use different URL for different architectures. Now it use same URL. This causes we have to fix URL every time. Relates to microsoft/winget-pkgs#121602 , microsoft/winget-pkgs#121707 and microsoft/winget-pkgs#121631

**Comment by vedantmgoyal9** [comment]
* https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/1395
