### ISSUE TITLE
[New Package]: Kiraku.AudioJam

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#309]
### List the PackageIdentifier of the package to be added to automation

Kiraku.AudioJam

### Details about the application

Similar to https://github.com/vedantmgoyal2009/vedantmgoyal200/issues/162 and https://github.com/vedantmgoyal2009/vedantmgoyal200/issues/163

https://api.kirakuapp.com/auth/version/latest?appId=4&platform=0
InstallerUrl: `$result.data.downloadUrl`
PackageVersion: From InstallerUrl
ReleaseDate: `$result.data.createTime` or `$result.data.updateTime`, and convert to UTC+8 time
```PowerShell
$time = [System.DateTimeOffset]::FromUnixTimeMilliseconds($result.data.createTime)
[System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId($time, 'China Standard Time').ToString('yyyy-MM-dd')
```

**Comment by vedantmgoyal9** [comment]
![image](https://user-images.githubusercontent.com/83997633/157248935-f8c5aa90-6a61-43a4-9b34-321dec0d4e74.png)
![image](https://user-images.githubusercontent.com/83997633/157248994-2dd5b620-5879-4e1b-a94b-bdef65f2f119.png)

**Comment by SpecterShell** [comment]
`Get`, not `Post`

**Comment by vedantmgoyal9** [comment]
`Get` also does not work.

**Comment by SpecterShell** [comment]
That is strange. It can be opened in the browser directly without any errors, which means `Get` should work at least.
Did you forget to append `?appId=4&platform=0` to the `Uri` and delete that in the `Body`?

**Comment by vedantmgoyal9** [comment]
So it works now. Also, I haven't converted the timezone since the date remains same after the conversion. If we had to get the exact time, then it would have made sense to convert it to UTC+8 time.
