### ISSUE TITLE
[New Package]: Minusium.MicaForEveryone

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal9/winget-pkgs-automation#353]
### List the PackageIdentifier of the package to be added to automation

Minusium.MicaForEveryone

### Details about the application

https://github.com/MicaForEveryone/MicaForEveryone
https://github.com/MicaForEveryone/MicaForEveryone/releases/download/v1.0.6.3/MicaForEveryone-v1.0.6.3-x64-Release.msixbundle

**Comment by sitiom** [comment]
Oops
![image](https://user-images.githubusercontent.com/56180050/159296529-2f719bca-2335-4230-9fed-5e7e823ba097.png)

**Comment by vedantmgoyal9** [comment]
No problem, once you fix that, you can comment here and tell me.

**Comment by sitiom** [comment]
https://github.com/minusium/MicaForEveryone/issues/36 would have to be sorted out first.

**Comment by xmine64** [comment]
You need to install my custom certificate to be able to install it.

**Comment by sitiom** [comment]
> You need to install my custom certificate to be able to install it.

Like I said in https://github.com/minusium/MicaForEveryone/issues/36#issuecomment-1074116748, not secure and not supported. The blocker here is waiting for the Microsoft Store release, which is being discussed in https://github.com/minusium/MicaForEveryone/issues/36.

**Comment by vedantmgoyal9** [comment]
Since Mica is being made available on Microsoft Store, and WinGet supports installing from Microsoft Store... it doesn't need to be there in winget-pkgs repo.

**Comment by sitiom** [comment]
It can be both, right? Like Windows Terminal?

**Comment by xmine64** [comment]
Btw project link is no longer valid, it's https://github.com/minusium/MicaForEveryone now.

**Comment by sitiom** [comment]
You mean https://github.com/MicaForEveryone/MicaForEveryone, updated links.

**Comment by sitiom** [comment]
https://github.com/MicaForEveryone/MicaForEveryone/pull/102
