### ISSUE TITLE
[New Package]: FrancisBanyikwa.SiriKali

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal9/winget-pkgs-automation#354]
### List the PackageIdentifier of the package to be added to automation

FrancisBanyikwa.SiriKali

### Details about the application

https://github.com/mhogomchungu/sirikali
https://github.com/mhogomchungu/sirikali/releases/download/1.5.0/SiriKali-1.5.0.setup.exe

https://github.com/microsoft/winget-pkgs/pull/55279

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @sitiom for ideas
