### ISSUE TITLE
[New Package]: CiderCollective.Cider.Nightly

### ISSUE THREAD

**Issue by yazninja** [vedantmgoyal9/winget-pkgs-automation#355]
### List the PackageIdentifier of the package to be added to automation

CiderCollective.Cider.Nightly

### Details about the application

Source: https://github.com/ciderapp/Cider/tree/develop
We created a repo for releases: https://github.com/ciderapp/cider-releases/releases
Also, idk why but the installers default to x32 architecture which I have to manually change every time to x64

PR: https://github.com/microsoft/winget-pkgs/pull/55271

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @yazninja for ideas
