### ISSUE TITLE
[New Package]: zotero.zotero

### ISSUE THREAD

**Issue by lychichem** [vedantmgoyal9/winget-pkgs-automation#366]
### List the PackageIdentifier of the package to be added to automation

Zotero.zotero

### Details about the application

PackageIdentifier: Zotero.Zotero
PackageLocale: en-US
Publisher: Corporation for Digital Scholarship
PublisherSupportUrl: https://www.zotero.org/support/
PrivacyUrl: https://www.zotero.org/support/privacy
PackageName: Zotero
PackageUrl: https://www.zotero.org/
License: AGPL-3.0-only
LicenseUrl: https://github.com/zotero/zotero/blob/master/COPYING
Copyright: Copyright (c) 2006-2022 Corporation for Digital Scholarship
CopyrightUrl: https://github.com/zotero/zotero/blob/master/COPYING
ShortDescription: Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research.
Moniker: zotero
Tags:
- reasearch
- collect
- organize
- cite
- share
ReleaseNotesUrl: https://www.zotero.org/support/changelog
InstallerURL:`https://www.zotero.org/download/client/dl?channel=release&platform=win32&version=<version number>`

**Comment by vedantmgoyal9** [comment]
Hey, you don't need to provide details from the Locale manifest, just the API/Source, and the details about how to fetch PackageVersion and Installer Urls, or if available ReleaseDate and ReleaseNotes. Alternatively, you can take a look at the issues opened by @SpecterShell to get an idea 😁

**Comment by SpecterShell** [comment]
Update source:
https://www.zotero.org/download/client/update/0/0/WINNT_x86/en-US/release/update.xml
