### ISSUE TITLE
[Bug]: Please add a check for "develop" in CiderCollective.Cider.Nightly

### ISSUE THREAD

**Issue by yazninja** [vedantmgoyal9/winget-pkgs-automation#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, first of all, I love your work, thanks for automating winget package making for our app.

I made this issue because we have added releases for our other branches and it has also been added to the winget repo even though it was never meant to be there. Please add a check to see if the name of the release ends with (develop), if not, please do not add to the winget repo.

Thanks so much,
Yaz

**Comment by vedantmgoyal9** [comment]
> Hi, first of all, I love your work, thanks for automating winget package making for our app.

Thank you🙏🎉

> I made this issue because we have added releases for our other branches and it has also been added to the winget repo even though it was never meant to be there. Please add a check to see if the name of the release ends with (develop), if not, please do not add to the winget repo.

I think we can add releases with "main" to the stable package identifier "CiderCollective.Cider.Nightly". If yes, you can make an initial PR for it at winget-pkgs repository so that I can add that to the automation too after that PR is merged.

**Comment by yazninja** [comment]
> > Hi, first of all, I love your work, thanks for automating winget package making for our app.
> 
> Thank you🙏🎉
> 
> > I made this issue because we have added releases for our other branches and it has also been added to the winget repo even though it was never meant to be there. Please add a check to see if the name of the release ends with (develop), if not, please do not add to the winget repo.
> 
> I think we can add releases with "main" to the stable package identifier "CiderCollective.Cider.Nightly". If yes, you can make an initial PR for it at winget-pkgs repository so that I can add that to the automation too after that PR is merged.

Hi, sorry it took a while for me to respond, I hope you may reopen this issue, My PRs have been merged to `winget-pkgs`, also updated the version number in the packages

**Comment by yazninja** [comment]
Hi, the check does not work i think, both cider and cider.nightly pull the same package...
