### ISSUE TITLE
[New Package]: Giorgiotani.Peazip

### ISSUE THREAD

**Issue by OfficialEsco** [vedantmgoyal9/winget-pkgs-automation#383]
### List the PackageIdentifier of the package to be added to automation

Giorgiotani.Peazip

### Details about the application

GitHub release
Look for exe and msi

**Comment by vedantmgoyal2009** [comment]
Already there: https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/g/giorgiotani.peazip.json
