### ISSUE TITLE
[New Package]: Dummerle.Rare

### ISSUE THREAD

**Issue by OfficialEsco** [vedantmgoyal9/winget-pkgs-automation#385]
### List the PackageIdentifier of the package to be added to automation

Dummerle.Rare

### Details about the application

GitHub release
Look for msi

**Comment by kxxoling** [comment]
Dummerle.Rare just released a new version https://github.com/Dummerle/Rare/releases/tag/1.9.2

**Comment by vedantmgoyal9** [comment]
* The PRs are not created due to https://github.com/actions/runner-images/issues/6446.

Once it is resolved, I'll revert the commits and re-run the automatioin again.
