### ISSUE TITLE
[New Package]: Wondershare.*

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#399]
### List the PackageIdentifier of the package to be added to automation

Wondershare.* and EdrawSoft.*

### Details about the application

Wondershare.CreativeCenter
https://pc-api.300624.com/v2/product/check-upgrade?pid=10819&client_sign=%7B%7D&version=1.0.0.0&platform=win_x64
PackageVersion: `$Response.data.version`
InstallerUrl: `"https://download.wondershare.com/cbs_down/wondershareCC_$($version)_full10819.exe"`
ReleaseNotes: `$Response.data.whats_new_content`

**Comment by SpecterShell** [comment]
Wondershare.MobileTrans
https://pc-api.300624.com/v2/product/check-upgrade?pid=5793&client_sign=%7B%7D&version=3.5.1.0&platform=win_x86
InstallerUrl: `"https://download.wondershare.com/cbs_down/mobiletrans_$($Response.data.version)_full5793.exe"`

**Comment by SpecterShell** [comment]
Wondershare.Recoverit
https://pc-api.300624.com/v2/product/check-upgrade?pid=4134&client_sign=%7B%7D&version=7.0.0&platform=win_x64
PackageVersion: From installer `(Get-Item .\recoverit_64bit_10.1.4_full4134.exe).VersionInfo.ProductVersion`
InstallerUrl: `"https://download.wondershare.com/cbs_down/recoverit_64bit_$($Response.data.version)_full4134.exe"`

**Comment by SpecterShell** [comment]
Wondershare.Anireel
https://pc-api.300624.com/v2/product/check-upgrade?pid=9589&client_sign=%7B%7D&version=1.0.0.0&platform=win_x64
InstallerUrl: `"https://download.wondershare.com/cbs_down/anireel_64bit_$($Response.data.version)_full9589.exe"`

**Comment by SpecterShell** [comment]
Wondershare.DemoCreator
https://pc-api.300624.com/v2/product/check-upgrade?pid=7743&client_sign=%7B%7D&version=4.0.0.0&platform=win_x64
PackageVersion: From installer
InstallerUrl: `"https://download.wondershare.com/cbs_down/democreator_$($Response.data.version)_full7743.exe"`

**Comment by SpecterShell** [comment]
Wondershare.Filmii
https://pc-api.300624.com/v2/product/check-upgrade?pid=7771&client_sign=%7B%7D&version=1.0.0.0&platform=win_x64
PackageVersion: From installer
InstallerUrl: `"https://download.wondershare.com/cbs_down/filmii_64bit_$($Response.data.version)_full7771.exe"`

**Comment by SpecterShell** [comment]
Wondershare.Filmora
https://pc-api.300624.com/v2/product/check-upgrade?pid=846&client_sign=%7B%7D&version=10.5.0.0&platform=win_x64
PackageVersion: From installer
InstallerUrl: `"https://download.wondershare.com/cbs_down/filmora_64bit_$($Response.data.version)_full846.exe"`

**Comment by vedantmgoyal9** [comment]
@SpecterShell please do EdrawSoft.* in a separate issue. Also, there are a total of 14 packages, and there are only 7. The missing ones are:
- DVDCreator
- Filmora.CN 
- MirrorGo
- PDFelement
- UniConverter
- UniConverter.13
- UniConverter.CN

**Comment by vedantmgoyal2009** [comment]
Hey, any status about these?

**Comment by SpecterShell** [comment]
There are 20 more packages from Wondershare to be added to winget-pkgs. I will complete this list after that.

If you want to add these packages to automation now, you can take a look at this 😉:
https://gist.github.com/SpecterShell/cc26e80d7b3259bab50eb33e2842887d
(v2 API doesn't need auth)

**Comment by vedantmgoyal9** [comment]
Oh, thanks! I will add the packages to the automation. However, whenever you will make PR and the package will be added, the automation would update them.

(Yes, adding a package here "before" than in winget-pkgs wouldn't break anything. It would continue without any error since YamlCreate does NOT throw when it cannot find the package folder and proceeds further to update the next package.)

**Comment by SpecterShell** [comment]
Wondershare.UBackit
https://cbs.wondershare.com/go.php?m=upgrade_info&pid=8767&version=1.0.0.0
PackageVersion: From installer
InstallerUrl: `"https://download.wondershare.com/cbs_down/ubackit_$($Response.Respone.WhatNews.Item[0].Version)_full8767.exe"`
ReleaseNotes: `$Response.Respone.WhatNews.Item[0].Text.'#cdata-section'`

**Comment by SpecterShell** [comment]
Wondershare.Mockitt.CN
https://modao.cc/api/v2/client/desktop/check_update.json?region=CN&version=1.1.0&platform=win32&arch=x64

PackageVersion: `$Response.version`
InstallerUrl:
x86: `"https://cdn.modao.cc/Mockitt-win32-ia32-zh-$($Response.version).exe"`
x64: `"https://cdn.modao.cc/Mockitt-win32-x64-zh-$($Response.version).exe"`
ReleaseDate: `$Response.pub_date`
ReleaseNotes: `$Response.release_notes_zh` (Do not use `$Response.release_notes_en` as it is no longer updated here)

**Comment by SpecterShell** [comment]
Wondershare.PDFReader
https://cbs.wondershare.com/go.php?m=upgrade_info&pid=13142&version=1.0.0.0

PackageVersion: `$Response.Respone.WhatNews.Item[0].Version`
InstallerUrl:
`"https://download.wondershare.com/cbs_down/pdfreader_$($Version)_full13142.exe"`
`"https://download.wondershare.com/cbs_down/pdfreader_64bit_$($Version)_full13142.exe"`
ReleaseNotes: `$Response.Respone.WhatNews.Item[0].Text.'#cdata-section'`

PR: https://github.com/microsoft/winget-pkgs/pull/59075

**Comment by SpecterShell** [comment]
Wondershare.PDFelement.CN
https://cbs.wondershare.com/go.php?m=upgrade_info&pid=5387&version=8.0.0.0

PackageVersion: `$Response.Respone.WhatNews.Item[0].Version`
InstallerUrl:
`"https://cc-download.wondershare.cc/cbs_down/pdfelement_$($Version)_full5387.exe"`
`"https://cc-download.wondershare.cc/cbs_down/pdfelement_64bit_$($Version)_full5387.exe"`
ReleaseNotes: `$Response.Respone.WhatNews.Item[0].Text.'#cdata-section'`

**Comment by vedantmgoyal9** [comment]
> Wondershare.PDFelement.CN

Can you please tell how to fix the characters in Release Notes?

![image](https://user-images.githubusercontent.com/83997633/180592989-15a9fa52-1516-4feb-b9c7-ba481c08976b.png)

**Comment by SpecterShell** [comment]
```PowerShell
$Response = Invoke-WebRequest -Uri 'https://cbs.wondershare.com/go.php?m=upgrade_info&pid=5387&version=8.0.0.0'
[System.IO.StreamReader]::new($Response.RawContentStream).ReadToEnd()
```

**Comment by SpecterShell** [comment]
~~You can use the third method for the packages in the first one, and vice versa.~~
**InstallerUrl should be obtained by building the URL directly instead of taking the one from the source.**

- Packages that use `"https://cbs.wondershare.com/go.php?m=upgrade_info&pid=${ProductId}&version=${Version}"`

  | PackageIdentifier         | ProductId | Version | Read ProductVersion from installer? |
  | ------------------------- | --------- | ------- | ----------------------------------- |
  | Wondershare.DVDCreator    | 619       | 4.0.0.0 | true                                |
  | Wondershare.MirrorGo      | 8050      | 1.0.0.0 | true                                |
  | Wondershare.PDFelement    | 5239      | 7.0.0.0 | false                               |
  | Wondershare.PDFelement.CN | 5387      | 8.0.0.0 | false                               |
  | Wondershare.PDFReader     | 13142     | 1.0.0.0 | false                               |
  | Wondershare.PDFReader.CN  | 13143     | 1.0.1   | false                               |
  | Wondershare.UBackit       | 8767      | 1.0.0.0 | true                                |



- Packages that use `"http://platform.wondershare.com/rest/v2/downloader/runtime/?product_id=${ProductId}&wae=${Wae}"`

  | PackageIdentifier        | ProductId | Wae     | Read ProductVersion from installer? |
  | ------------------------ | --------- | ------- | ----------------------------------- |
  | Wondershare.Recoverit    | 4134      | 3.0.3   | true                                |
  | Wondershare.Recoverit.CN | 4516      | 3.0.3   | true                                |
  | Wondershare.Repairit     | 5913      | (empty) | true                                |

  

- Packages that use

   `"https://pc-api.300624.com/v2/product/check-upgrade?pid=${ProductId}&client_sign={}&version=${Version}&platform=win_$($x86 ? 'x86' : 'x64')"`

  or

  `"https://pc-api.wondershare.cc/v2/product/check-upgrade?pid=${ProductId}&client_sign={}&version=${Version}&platform=win_$($x86 ? 'x86' : 'x64')"`

  | PackageIdentifier           | ProductId | Version  | x86   | Read ProductVersion from installer? |
  | --------------------------- | --------- | -------- | ----- | ----------------------------------- |
  | Wondershare.Anireel         | 9589      | 1.0.0.0  | false | false                               |
  | Wondershare.CreativeCenter  | 10819     | 1.0.0.0  | false | false                               |
  | Wondershare.DemoCreator     | 7743      | 4.0.0.0  | false | true                                |
  | Wondershare.DemoCreator.CN  | 13164     | 5.2.0.0  | false | false                               |
  | Wondershare.Filmii          | 7771      | 1.0.0.0  | false | true                                |
  | Wondershare.Filmora         | 846       | 10.0.0.0 | false | true                                |
  | Wondershare.Filmora.CN      | 3223      | 5.0.0.0  | false | true                                |
  | Wondershare.MobileTrans     | 5793      | 1.0.0.0  | true  | false                               |
  | Wondershare.UniConverter.13 | 9629      | 13.0.0   | false | true                                |
  | Wondershare.UniConverter.CN | 4981      | 11.0.0   | false | true                                |
  | Wondershare.WXRecovery      | 7546      | 1.0.0    | false | true                                |

**Comment by SpecterShell** [comment]
There is also a batch upgrade API:
```PowerShell
Invoke-RestMethod -Uri 'https://pc-api.300624.com/v2/product/batch-check-upgrade' -Method Post -Body @"
{
  "platform": "win_x64",
  "versions": [
    {
      "version": "1.0.0.0",
      "pid": "9589"
    },
    {
      "version": "1.0.0.0",
      "pid": "10819"
    },
    {
      "version": "4.0.0.0",
      "pid": "7743"
    },
    {
      "version": "5.2.0.0",
      "pid": "13164"
    },
    {
      "version": "1.0.0.0",
      "pid": "7771"
    },
    {
      "version": "10.0.0.0",
      "pid": "846"
    },
    {
      "version": "5.0.0.0",
      "pid": "3223"
    },
    {
      "version": "7.0.0.0",
      "pid": "5239"
    },
    {
      "version": "1.0.0.0",
      "pid": "13142"
    },
    {
      "version": "1.0.1",
      "pid": "13143"
    },
    {
      "version": "13.0.0",
      "pid": "9629"
    },
    {
      "version": "11.0.0",
      "pid": "4981"
    },
    {
      "version": "1.0.0",
      "pid": "7546"
    }
  ]
}
"@
```
You can use it to avoid exceeding limits.

**Comment by vedantmgoyal2009** [comment]
Wondershare Filmora returns old version.

**Comment by vedantmgoyal9** [comment]
https://pc-api.300624.com/v2/product/check-upgrade?pid=5793&client_sign=%7B2AF6BA4A-E8CF-4DCA-95FC-09F49FC6E761%7D&version=1.0.0.0&platform=win_x86

Wondershare.MobileTrans not working

Edit: Working, version needs to be `3.5.1.0`

**Comment by vedantmgoyal2009** [comment]
Wondershare Recoverit also returns old version.

**Comment by vedantmgoyal2009** [comment]
Wondershare.Repairit.CN returns non-existing version.

**Comment by vedantmgoyal9** [comment]
@SpecterShell some inputs are needed here too.

- Wondershare Filmora returns old version. (`API: 11.6.7`, `Current version in the repo:` [11.7.3.814](https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/Wondershare/Filmora/11.7.3.814))
- Wondershare.Repairit.CN returns non-existing version. (`http://platform.wondershare.com/rest/v2/downloader/runtime/?product_id=11009&wae=3.0.3` `https://cc-download.wondershare.cc/cbs_down/repairit_#version_full11009.exe`) Is that the reason you didn't include it in the list?
- Also, PDFelement is now splitted into major versions. I've added only PDFelement 9. Is there any need to include 8 and previous versions? Do they receive updates?
- Not an issue, just to let you know: I've added FamiSafe: `https://cbs.wondershare.com/go.php?m=upgrade_info&pid=7740&version=1.0.0.0` 🙂
- Also, many packages don't have version-specific installer URLs, so I hope after the above issues are resolved, this issue can be closed. That was a lot of packages 😪

**Comment by SpecterShell** [comment]
> * Wondershare Filmora returns old version. (`API: 11.6.7`, `Current version in the repo:` [11.7.3.814](https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/Wondershare/Filmora/11.7.3.814?rgh-link-date=2022-10-02T05%3A09%3A48Z))

It updated to `11.7.3.814` last week but rolled back to `11.6.7` some days later.

> * Wondershare.Repairit.CN returns non-existing version. (`http://platform.wondershare.com/rest/v2/downloader/runtime/?product_id=11009&wae=3.0.3` `https://cc-download.wondershare.cc/cbs_down/repairit_#version_full11009.exe`) Is that the reason you didn't include it in the list?

Yes as I expected wingetbot to detect its updates. It is welcomed if you want to take over it.

> * Also, PDFelement is now splitted into major versions. I've added only PDFelement 9. Is there any need to include 8 and previous versions? Do they receive updates?

Only 9 is needed because 8 and 9 have the same upgrade API. 7- are deprecated and no longer update.

> * Not an issue, just to let you know: I've added FamiSafe: `https://cbs.wondershare.com/go.php?m=upgrade_info&pid=7740&version=1.0.0.0` 🙂

FamiSafe hasn't been updated for a long time until last week, after which it has versioned links.

BTW i'm moving `Wondershare.DemoCreator` and `Wondershare.Filmora.CN` to X.Y.Z versions so that downloading and ProductVersion parsing are no longer needed for these packages.

**Comment by SpecterShell** [comment]
Most packages that don't have versioned links haven't been updated for years, so you can just ignore them.

**Comment by vedantmgoyal9** [comment]
> BTW i'm moving `Wondershare.DemoCreator` and `Wondershare.Filmora.CN` to X.Y.Z versions so that downloading and ProductVersion parsing are no longer needed for these packages.

Okay, mention me again when all PRs have been merged.

**Comment by SpecterShell** [comment]
@vedantmgoyal2009 merged
