### ISSUE TITLE
[New Package]: AppbyTroye.KoodoReader

### ISSUE THREAD

**Issue by OfficialEsco** [vedantmgoyal9/winget-pkgs-automation#402]
### List the PackageIdentifier of the package to be added to automation

AppbyTroye.KoodoReader

### Details about the application

GitHub Release https://github.com/troyeguo/koodo-reader/releases
Look for `Koodo-Reader-<Version>.exe`

**Comment by fdsfdfg** [comment]
大佬能否适配一下安卓平台😂
