### ISSUE TITLE
[New Package]: Redisant.*

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#416]
### List the PackageIdentifier of the package to be added to automation

Redisant.RedisAssistant

### Details about the application

https://www.redisant.com/activate/checkUpdate

PackageVersion: `$Response.version`
InstallerUrl: `$Response.enDownloadUrl`
ReleaseNotes: ~~`$Response.enDescribes[0]`~~
```PowerShell
$Response.enDescribes[0..($Response.enDescribes.Length - 2)] -replace '^','- ' -join "`n"
```
InstallerSha256: `$Response.enDescribes[-1]`

PR: https://github.com/microsoft/winget-pkgs/pull/58788

**Comment by SpecterShell** [comment]
### List the PackageIdentifier of the package to be added to automation

Redisant.DataAssistant

### Details about the application

https://www.redisant.com/da/activate/checkUpdate

PR: https://github.com/microsoft/winget-pkgs/pull/58793

**Comment by SpecterShell** [comment]
### List the PackageIdentifier of the package to be added to automation

Redisant.LittleTips

### Details about the application

https://www.redisant.com/lt/activate/checkUpdate

No checksum

**Comment by SpecterShell** [comment]
### List the PackageIdentifier of the package to be added to automation

Redisant.ZooKeeperAssistant

### Details about the application

https://www.redisant.com/za/activate/checkUpdate

PR: https://github.com/microsoft/winget-pkgs/pull/58870

**Comment by SpecterShell** [comment]
### List the PackageIdentifier of the package to be added to automation

Redisant.KafkaAssistant

### Details about the application

https://www.redisant.com/ka/activate/checkUpdate

PR: https://github.com/microsoft/winget-pkgs/pull/58873

**Comment by vedantmgoyal9** [comment]
TinyGUI is still left.

**Comment by SpecterShell** [comment]
TinyGUI doesn't have update source.

**Comment by SpecterShell** [comment]
Redisant.RabbitMQAssistant

https://www.redisant.com/rta/activate/checkUpdate
