### ISSUE TITLE
[New Package]: Bilibili.Bilibili

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#490]
### List the PackageIdentifier of the package to be added to automation

Bilibili.Bilibili

### Details about the application

```PowerShell
$Response = Invoke-RestMethod -Uri 'https://api.bilibili.com/x/elec-frontend/update/latest.yml' | ConvertFrom-Yaml
$InstallerUrl = (Invoke-WebRequest -Uri "https://api.bilibili.com/x/elec-frontend/update/$($Response.files.url)" -Method Head -Headers @{appversion='0'}).BaseResponse.RequestMessage.RequestUri.AbsoluteUri
```

PR: https://github.com/microsoft/winget-pkgs/pull/62215

**Comment by vedantmgoyal9** [comment]
![image](https://user-images.githubusercontent.com/83997633/172771873-afe1e287-b42d-4db9-a92a-1a7dc6d27d43.png)

**Comment by SpecterShell** [comment]
`appversion=0` is a request header entry, not a param in the URL.
