### ISSUE TITLE
[Bug]: Mozilla.Thunderbird.Beta not getting updated

### ISSUE THREAD

**Issue by RyanHir** [vedantmgoyal9/winget-pkgs-automation#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Project Name

WinGet Automation

### What happened?

Mozilla.Thunderbird.Beta is not updating after upstream reached version 100.

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @RyanHir for bug
