### ISSUE TITLE
[New Package]: Tencent.qq

### ISSUE THREAD

**Issue by lychichem** [vedantmgoyal9/winget-pkgs-automation#508]
### List the PackageIdentifier of the package to be added to automation

Tencent.QQ

### Details about the application

InstallModes:
- interactive
- silent

InstallerSwitches:

-   Silent: /S

-  SilentWithProgress: /S
  
InstallLocation: '"`path<INSTALLPATH>`" "`notify0`"'

UpgradeBehavior: install

Protocols:
- tencent

FileExtensions:
- eif
- eip
- kipx

AppsAndFeaturesEntries:
- DisplayName: 腾讯QQ
  Publisher: 腾讯科技(深圳)有限公司
  InstallerType: msi

Installers:
- Architecture: x86
  InstallerUrl: `https://dldir1.qq.com/qqfile/qq/PCQQ<first 3 part of version number>/QQ<full version number>.exe`

Product code needed as it is an msi packed in nsis installer.

**Comment by lychichem** [comment]
See: https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/Tencent/QQ

**Comment by vedantmgoyal9** [comment]
@SpecterShell

**Comment by SpecterShell** [comment]
Patch update
Parse download page instead

**Comment by vedantmgoyal9** [comment]
Please give download page link
