### ISSUE TITLE
[New Package]: RustDesk.RustDesk

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal9/winget-pkgs-automation#556]
### List the PackageIdentifier of the package to be added to automation

RustDesk.RustDesk

### Details about the application

https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-x64.exe
https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-x32.exe

PR: https://github.com/microsoft/winget-pkgs/pull/63466

**Comment by vedantmgoyal9** [comment]
* https://github.com/rustdesk/rustdesk/pull/785
