### ISSUE TITLE
[New Package]: Qingfeng.HeyboxWow

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#558]
### List the PackageIdentifier of the package to be added to automation

Qingfeng.HeyboxWow

### Details about the application

https://accoriapi.xiaoheihe.cn/wow/check_new_version_v2/

PackageVersion: `$Response.result.new_version`
InstallerUrl: `$Response.result.url`
ReleaseNotes: ```[regex]::Matches($Response.result.change_log, '(?<=<li>).+?(?=</li>)').Value -creplace '^', '- ' -join "`n"```

PR: https://github.com/microsoft/winget-pkgs/pull/63546

**Comment by vedantmgoyal9** [comment]
You've closed the winget pull request. However, it looks like you've missed `/` in `InstallerSwitches`:

https://github.com/SpecterShell/winget-pkgs/blob/bd68a8e397a466d5934d3ca4db7ff7fb7c52bfdf/manifests/q/Qingfeng/HeyboxWow/1.8.2/Qingfeng.HeyboxWow.installer.yaml#L12-L14
