### ISSUE TITLE
[New Package]: PortSwigger.BurpSuite.*

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#563]
### List the PackageIdentifier of the package to be added to automation

PortSwigger.BurpSuite.Community

### Details about the application

https://portswigger.net/Burp/Releases/CheckForUpdates?product=community&channel=Stable&version=0

PackageVersion: `$Response.updates[0].version`
InstallerUrl: `"https://portswigger-cdn.net/burp/releases/download?product=community&version=${Version}&type=WindowsX64"`
ReleaseNotes: `$Response.updates[0].description`
ReleaseNotesUrl: `$Response.updates[0].releaseNotesUrl`

**Comment by SpecterShell** [comment]
### List the PackageIdentifier of the package to be added to automation

PortSwigger.BurpSuite.Professional

### Details about the application

~https://portswigger.net/Burp/Releases/CheckForUpdates?product=pro&channel=Stable&version=0~

All the same to PortSwigger.BurpSuite.Community, but
InstallerUrl: `"https://portswigger-cdn.net/burp/releases/download?product=pro&version=${Version}&type=WindowsX64"`

**Comment by vedantmgoyal9** [comment]
Did you find Enterprise?

**Comment by SpecterShell** [comment]
https://portswigger-cdn.net/burp/releases/download?product=enterprise&version=2022.5&type=WindowsX64
https://portswigger.net/Burp/Releases/CheckForUpdates?product=enterprise&channel=Stable&version=0

The installer of the enterprise edition is packed in a zip archive, and its update source requires license as well.

**Comment by vedantmgoyal9** [comment]
Oh, if it is ZIP, then it would make into winget-pkgs repo only 😅
