### ISSUE TITLE
[New Package]: LizardByte.Sunshine

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal9/winget-pkgs-automation#566]
### List the PackageIdentifier of the package to be added to automation

LizardByte.Sunshine

### Details about the application

https://github.com/LizardByte/Sunshine/releases/download/v0.14.0/sunshine-windows.exe

PR: https://github.com/microsoft/winget-pkgs/pull/63722

**Comment by sitiom** [comment]
https://github.com/LizardByte/Sunshine/pull/215

**Comment by vedantmgoyal9** [comment]
Thank you so much 🙂
