### ISSUE TITLE
[New Package]: Bosyun.Pixso

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#573]
### List the PackageIdentifier of the package to be added to automation

Bosyun.Pixso

### Details about the application

https://pixso-public.oss-accelerate.aliyuncs.com/cms/download/package/latest.yml

PR: https://github.com/microsoft/winget-pkgs/pull/63831

**Comment by vedantmgoyal9** [comment]
Source returns `1.28.0` whereas repository contains `1.3.0`

**Comment by SpecterShell** [comment]
Thanks reminding. I published the wrong version.
https://github.com/microsoft/winget-pkgs/pull/64169

**Comment by vedantmgoyal9** [comment]
Do you mean 1.3.0 is beta?

**Comment by SpecterShell** [comment]
1.28.0 is the current version and I publish the old version 1.3.0.😕
Isn't 28>3?

**Comment by vedantmgoyal9** [comment]
Oh, my bad... My brain was doing 2.8 < 3.0.
