### ISSUE TITLE
[New Package]: GeoffreyChen.Paperlib

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#584]
### List the PackageIdentifier of the package to be added to automation

GeoffreyChen.Paperlib

### Details about the application

https://github.com/GeoffreyChen777/paperlib/releases

PR: https://github.com/microsoft/winget-pkgs/pull/64459

**Comment by vedantmgoyal9** [comment]
It is recommended to use https://github.com/marketplace/actions/winget-releaser.

**Comment by vedantmgoyal9** [comment]
* https://github.com/GeoffreyChen777/paperlib/issues/130

**Comment by SpecterShell** [comment]
The latest version on the [official website](https://paperlib.app/en/download/) is greater than that on the repo's releases at the moment. I will take a look for some days. 🤔

**Comment by vedantmgoyal9** [comment]
* https://github.com/GeoffreyChen777/paperlib/pull/139
* https://github.com/GeoffreyChen777/paperlib/pull/140

**Comment by GeoffreyChen777** [comment]
Hi I found a issue:

```
Url validation error

manifests\g\GeoffreyChen\Paperlib\2.0.0
https://github.com/GeoffreyChen777/paperlib/blob/master/LICENCE
Http status code: NotFound
```

I think the reason is that I use `LICENSE` not `LICENCE` in my repo. How to fix this?

**Comment by SpecterShell** [comment]
You can simply replace the broken urls by editing the files in the PR.

**Comment by vedantmgoyal9** [comment]
* https://github.com/microsoft/winget-pkgs/pull/80149

**Comment by vedantmgoyal9** [comment]
@GeoffreyChen777 Commit the suggested changes on the PR, and next time, the action will automatically use the correct URL.

**Comment by GeoffreyChen777** [comment]
@vedantmgoyal2009 Hi could you please guide me how to do that ? PR to which repo? I'm really not familar with winget...

**Comment by vedantmgoyal9** [comment]
* https://github.com/microsoft/winget-pkgs/pull/80242

@GeoffreyChen777 Apply the suggested changes on the PR.

**Comment by GeoffreyChen777** [comment]
New Error, last week everything is fine:

```
Run vedantmgoyal2009/winget-releaser@latest
Install powershell-yaml, clone winget-pkgs and configure remotes, update YamlCreate, download wingetdev...
Update manifests and create pull request
  D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9765
        version || new RegExp(/(?<=v).*/g).exec(releaseInfo.tag_name)[0],
                                                                     ^
  
  TypeError: Cannot read properties of null (reading '0')
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9765:68
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
