### ISSUE TITLE
[New Package]: Rufus.Rufus

### ISSUE THREAD

**Issue by dwittenberg** [vedantmgoyal9/winget-pkgs-automation#594]
### List the PackageIdentifier of the package to be added to automation

Rufus.Rufus

### Details about the application

https://github.com/pbatard/rufus

**Comment by dwittenberg** [comment]
This package can at the moment not auto update

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @dwittenberg for ideas

**Comment by vedantmgoyal9** [comment]
* https://github.com/pbatard/rufus/issues/2046

**Comment by Silther** [comment]
@vedantmgoyal2009, @pbatard, @dwittenberg 
Why is the portable version ``rufus-3.21p.exe`` and not ``rufus-3.21.exe`` installed?
The installer does not create a start menu shortcut, which makes the app difficult to open for beginners, and the CLI command ``start rufus`` opens a folder and not the app.
