### ISSUE TITLE
[New Package]: ViGEm.HidHide

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal9/winget-pkgs-automation#596]
### List the PackageIdentifier of the package to be added to automation

ViGEm.HidHide

### Details about the application

https://github.com/ViGEm/HidHide/

PR: https://github.com/microsoft/winget-pkgs/pull/65528

**Comment by sitiom** [comment]
https://github.com/ViGEm/HidHide/pull/80

**Comment by vedantmgoyal9** [comment]
* Closing in favor of: https://github.com/ViGEm/HidHide/pull/80

**Comment by sitiom** [comment]
@vedantmgoyal2009 Author has decided to disable the workflow
- https://github.com/microsoft/winget-pkgs/pull/124362#issuecomment-1787188731
