### ISSUE TITLE
[New Package]: RemNote.RemNote

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#610]
### List the PackageIdentifier of the package to be added to automation

RemNote.RemNote

### Details about the application

https://download.remnote.io/latest.yml

**Comment by vedantmgoyal9** [comment]
Access Denied: https://download.remnote.io/RemNote%20Setup%201.8.8.exe

**Comment by SpecterShell** [comment]
https://download.remnote.io/RemNote%20Setup%201.8.7.exe
Accessing non-existent files also results in Access Denied. I thought they revoked the new installer for some reasons but forgot to rollback the update source. 🤔

**Comment by SpecterShell** [comment]
You can add this now.
