### ISSUE TITLE
[New Package]: RoyQu.RedPanda-C++

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#683]
### List the PackageIdentifier of the package to be added to automation

RoyQu.RedPanda-C++

### Details about the application

https://github.com/royqh1979/RedPanda-CPP/releases

**Comment by vedantmgoyal9** [comment]
I don't know Chinese, so can you request them if they would like to use winget releases?

**Comment by SpecterShell** [comment]
Asking in English is also OK. 🤔
https://github.com/royqh1979/RedPanda-CPP/issues/37

**Comment by vedantmgoyal9** [comment]
* https://github.com/royqh1979/RedPanda-CPP/pull/54
