### ISSUE TITLE
Turn on issues on winget-releaser

### ISSUE THREAD

**Issue by russellbanks** [vedantmgoyal9/winget-pkgs-automation#694]
### Project Name

WinGet Releaser Action

### What would you like to see changed/added?

Please turn on issues on [winget-releaser](https://github.com/vedantmgoyal2009/winget-releaser); it doesn't make sense to make issues about it here as the source code is now kept there.

**Comment by vedantmgoyal9** [comment]
Done! I'll update issue templates this weekend.

**Comment by russellbanks** [comment]
Thanks :D

**Comment by russellbanks** [comment]
https://github.com/vedantmgoyal2009/winget-releaser/pull/2
