### ISSUE TITLE
Github packages extract 2021-09-28

### ISSUE THREAD

**Issue by Trenly** [vedantmgoyal9/winget-pkgs-automation#7]
**List the PackageIdentifier of packages to be added to automation**
- [GithubPackages.csv](https://github.com/vedantmgoyal2009/winget-pkgs-automation/files/7247575/GithubPackages.csv)

**Comment by Trenly** [comment]
@vedantmgoyal2009  you may need a quick script to create the json for these; I don't know how you've been going about adding the asset_regex and the last_checked_tag for them, but it probably isn't feasible to do all of them manually

**Comment by vedantmgoyal2009** [comment]
Thanks, @Trenly. You made my work a lot easier. Once, I complete the automation script, I will merge this and would run my script (I will comment the part which generates and submits the manifests), then all the "last_checked_tag" will be updated to the latest tag in one go.

**Comment by Trenly** [comment]
> Thanks, @Trenly. You made my work a lot easier. Once, I complete the automation script, I will merge this and would run my script (I will comment the part which generates and submits the manifests), then all the "last_checked_tag" will be updated to the latest tag in one go.

Is there any way for me to stop the git tasks from running? I keep getting alerts about failed runs from my forked repo

**Comment by exoosh** [comment]
Hi there @vedantmgoyal2009 , just wondering. This `.csv` never made it in, right? Is there a way to contribute to the list of packages to be automated with identifier, regex and GitHub moniker?

I [commented here](https://github.com/johannesjo/super-productivity/issues/2618#issuecomment-1549521600) about a package that is already listed in the above `.csv`, but the `.csv` does not currently contain a regex, which would be needed to get the actual installer.

**Comment by vedantmgoyal9** [comment]
It exists here: https://github.com/vedantmgoyal2009/winget-manifests-manager/blob/main/packages/j/johannesmillan.superproductivity.json#L4

Actually, this was the repository where I kept all of my projects, combined in one place. But now, I'm organizing things little bit and as part of it, the automation has been moved to winget-manifests-manager.

**Comment by exoosh** [comment]
> It exists here: https://github.com/vedantmgoyal2009/winget-manifests-manager/blob/main/packages/j/johannesmillan.superproductivity.json#L4
> 
> Actually, this was the repository where I kept all of my projects, combined in one place. But now, I'm organizing things little bit and as part of it, the automation has been moved to winget-manifests-manager.

Oh wow, thanks. Your JSON lists the current version as expected (`7.13.2`), but when I searched in `winget-pkgs` for the identifier of this software, I didn't find anything. So I ended up [sending a PR](https://github.com/microsoft/winget-pkgs/pull/106907).

Has this automation been suspended or so?

Either way: thanks so much for your effort and help (you commented on past PRs from me, too).

**Comment by vedantmgoyal9** [comment]
> Has this automation been suspended or so?

I'm upgrading and fixing things. Will be live in some days again.
