### ISSUE TITLE
[New Package]: PostgreSQL.pgAdmin

### ISSUE THREAD

**Issue by dpprdan** [vedantmgoyal9/winget-pkgs-automation#703]
### List the PackageIdentifier of the package to be added to automation

PostgreSQL.pgAdmin

### Details about the application

Downloads available at: 

https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v{version}/windows/pgadmin4-{version}-x64.exe (overview: https://www.postgresql.org/ftp/pgadmin/pgadmin4/)

or alternatively

https://pgadmin-archive.postgresql.org/pgadmin4/v{version}/windows/pgadmin4-{version}-x64.exe (overview: https://pgadmin-archive.postgresql.org/pgadmin4/index.html) 

The former is used in current manifests, the latter provides more legacy versions (all apparently). 

The manifests use the same installer for both the machine and user scopes, see e.g. https://github.com/microsoft/winget-pkgs/blob/master/manifests/p/PostgreSQL/pgAdmin/6.12/PostgreSQL.pgAdmin.installer.yaml

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @dpprdan for ideas,doc

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @dpprdan for ideas, doc
