### ISSUE TITLE
[New Package]: gPodder

### ISSUE THREAD

**Issue by aman207** [vedantmgoyal9/winget-pkgs-automation#779]
### List the PackageIdentifier of the package to be added to automation

gpodder.gpodder

### Details about the application

Releases available via github

https://github.com/gpodder/gpodder/releases

**Comment by vedantmgoyal9** [comment]
It is recommended to use https://github.com/marketplace/actions/winget-releaser.

**Comment by aman207** [comment]
Thanks. I created an issue in the gpodder repo to see if they will add this

**Comment by vedantmgoyal9** [comment]
* https://github.com/gpodder/gpodder/issues/1378

**Comment by aman207** [comment]
PR https://github.com/gpodder/gpodder/pull/1380

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @aman207 for ideas

**Comment by vedantmgoyal9** [comment]
Added to https://docs.google.com/spreadsheets/d/1dnTRsRI8JdTyHibbBy8b1-Odd1gHJRjScm_KWUQ-jHk/edit?usp=sharing
