### ISSUE TITLE
[New Package]: OpenMedia.*

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#848]
### List the PackageIdentifier of the package to be added to automation

OpenMedia.4KVideoDownloader

### Details about the application

https://dl.4kdownload.com/app/appcast/videodownloader.xml

Replace suffix to get urls.

**Comment by vedantmgoyal9** [comment]
- [4KSlideshowMaker](https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenMedia/4KSlideshowMaker) - https://dl.4kdownload.com/app/appcast/slideshowmaker.xml

- [4KStogram](https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenMedia/4KStogram) - https://dl.4kdownload.com/app/appcast/stogram.xml

- [4KTokkit](https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenMedia/4KTokkit) - https://dl.4kdownload.com/app/appcast/tokkit.xml

- [4KVideoDownloader](https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenMedia/4KVideoDownloader) -https://dl.4kdownload.com/app/appcast/videodownloader.xml

- [4KVideoToMP3](https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenMedia/4KVideoToMP3) - https://dl.4kdownload.com/app/appcast/videotomp3.xml

- [4KYoutubetoMP3](https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenMedia/4KYoutubetoMP3) - https://dl.4kdownload.com/app/appcast/youtubetomp3.xml
