### ISSUE TITLE
[New Package]: Unity.Unity.*

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#868]
### List the PackageIdentifier of the package to be added to automation

Unity.Unity.*

### Details about the application

# The simple way

https://public-cdn.cloud.unity3d.com/hub/prod/releases-win32.json

Take Unity.Unity.2020 as example:
PackageVersion: `$Response.official.Where({$_.version.StartsWith('2020')}).version`
InstallerUrl: `$Response.official.Where({$_.version.StartsWith('2020')}).downloadUrl`

# The GraphQL way (contains releaseDate)

## Issue a GraphQL request by PSGraphQL module with Variable

```PowerShell
$query = @'
query GetUnityReleases($version: String) {
  getUnityReleases(
    stream: [TECH, LTS]
    platform: WINDOWS
    architecture: X86_64
    version: $version
  ) {
    edges {
      node {
        version
        releaseDate
        releaseNotes {
          url
        }
        downloads {
          ... on UnityReleaseHubDownload {
            url
          }
        }
      }
    }
  }
}
'@
# Or simplified
$query = 'query GetUnityReleases($version:String){getUnityReleases(stream:[TECH,LTS] platform:WINDOWS architecture:X86_64 version:$version){edges{node{version releaseDate releaseNotes{url} downloads{... on UnityReleaseHubDownload{url}}}}}}'
# Unity.Unity.2020
$Response = Invoke-GraphQLQuery -Uri 'https://live-platform-api.prd.ld.unity3d.com/graphql' -Query $query -OperationName "GetUnityReleases" -Variables '{"version": "2020"}'
# Unity.Unity.2021
$Response = Invoke-GraphQLQuery -Uri 'https://live-platform-api.prd.ld.unity3d.com/graphql' -Query $query -OperationName "GetUnityReleases" -Variables '{"version": "2021"}'
# Unity.Unity.2022
$Response = Invoke-GraphQLQuery -Uri 'https://live-platform-api.prd.ld.unity3d.com/graphql' -Query $query -OperationName "GetUnityReleases" -Variables '{"version": "2022"}'
$Response.data.getUnityReleases.edges[0].node | Format-List
```

## Issue a GraphQL request by PSGraphQL module without Variable

```PowerShell
$query = @'
query {
  getUnityReleases(
    stream: [TECH, LTS]
    platform: WINDOWS
    architecture: X86_64
    version: "2020"
  ) {
    edges {
      node {
        version
        releaseDate
        releaseNotes {
          url
        }
        downloads {
          ... on UnityReleaseHubDownload {
            url
          }
        }
      }
    }
  }
}
'@
# Or simplified
$query = 'query{getUnityReleases(stream:[TECH,LTS] platform:WINDOWS architecture:X86_64 version:"2020"){edges{node{version releaseDate releaseNotes{url} downloads{... on UnityReleaseHubDownload{url}}}}}}'
# Unity.Unity.2020
$Response = Invoke-GraphQLQuery -Uri 'https://live-platform-api.prd.ld.unity3d.com/graphql' -Query $query
$Response.data.getUnityReleases.edges[0].node | Format-List
```

## Issue a GraphQL request directly without Variable

```PowerShell
# Unity.Unity.2020
$Response = Invoke-RestMethod -Uri 'https://live-platform-api.prd.ld.unity3d.com/graphql' -Method POST -Body '{"query":"query{getUnityReleases(stream:[TECH,LTS] platform:WINDOWS architecture:X86_64 version:\"2020\"){edges{node{version releaseDate releaseNotes{url} downloads{... on UnityReleaseHubDownload{url}}}}}}"}' -ContentType 'application/json'
$Response.data.getUnityReleases.edges[0].node | Format-List
```

**Comment by vedantmgoyal9** [comment]
Please add the first version for Unity.Unity.2022 to winget-pkgs repo.

**Comment by vedantmgoyal9** [comment]
Also, GraphQL by JSON always returns the latest 2022 version no matter whatever I input in the `version` variable (`2019 | 2020 | 2021 | 2022`). The other 2 GraphQL methods I didn't test.

**Comment by SpecterShell** [comment]
Oh, sorry. Use lower case `version` in variables.

**Comment by SpecterShell** [comment]
I have updated all the code examples.

**Comment by SpecterShell** [comment]
I have updated the code examples again so that you can parse ReleaseNotes in Markdown format using this:

```PowerShell
((Invoke-RestMethod $Response.data.getUnityReleases.edges[0].node.releaseNotes.url | ConvertFrom-Markdown -AsVT100EncodedString).VT100EncodedString -creplace '\[(?:.*?)m(.+?)\[0m', '$1').Split("Release Notes")[1].Split("Packages updated")[0].Split("Package changes")[0].Split("System Requirements")[0].Trim() -creplace '(?m)^(\w.+)\n\n-', "`$1`n-"
```
`ConvertFrom-Markdown` is a PowerShell built-in cmdlet.

Updated: Add `Package changes` in splitting.

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/pull/82040

BTW for all versions you have to change the ReleaseNotesUrl and DocumentUrl.
For Unity 2021+ you also have to change ProductCode.

**Comment by vedantmgoyal9** [comment]
Reference: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.2

PowerShell issue: https://github.com/PowerShell/PowerShell/issues/16882

**Comment by vedantmgoyal9** [comment]
@SpecterShell please see https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/399 and https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/1192

**Comment by SpecterShell** [comment]
Please do not use the URL of the Markdown file as the ReleaseNotesUrl. There is a HTML version <https://unity3d.com/unity/whats-new/2021.1.0> and you can get its URL by concating strings.
