### ISSUE TITLE
[New Package]: voidtools.Everything

### ISSUE THREAD

**Issue by ppvnf** [vedantmgoyal9/winget-pkgs-automation#874]
### List the PackageIdentifier of the package to be added to automation

voidtools.Everything

### Details about the application

Installer URL: https://www.voidtools.com/downloads/

I noticed that voidtools.Everything.Lite is available at the same page - same version number than voidtools.Everything. 

Alternative download link: https://www.majorgeeks.com/files/details/everything.html

Winget-pkgs issue:
https://github.com/microsoft/winget-pkgs/issues/82462

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @ppvnf for ideas
