### ISSUE TITLE
[New Package]:  EverythingToolbar Beta

### ISSUE THREAD

**Issue by ppvnf** [vedantmgoyal9/winget-pkgs-automation#879]
### List the PackageIdentifier of the package to be added to automation

stnkl.EverythingToolbar.Beta

### Details about the application

I've seen that EverythingToolbar is already automated: https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/src/winget-pkgs-automation/packages/s/stnkl.everythingtoolbar.json
Could you please also automate the beta version of EverythingToolbar, since currently it's the only one that works on Windows 11?
Issue winget-pkgs: https://github.com/microsoft/winget-pkgs/issues/80628

**Comment by vedantmgoyal9** [comment]
Since the package is hosted on GitHub, you can request them to use https://github.com/marketplace/actions/winget-releaser.

**Comment by ppvnf** [comment]
https://github.com/stnkl/EverythingToolbar/issues/273
