### ISSUE TITLE
[New Package]: Rambox.Rambox

### ISSUE THREAD

**Issue by ppvnf** [vedantmgoyal9/winget-pkgs-automation#913]
### List the PackageIdentifier of the package to be added to automation

Rambox.Rambox

### Details about the application

A new version is available: https://github.com/ramboxapp/download/releases/tag/v2.0.7
I believe you are already know. Could you please update the automation script for the proprietary version?
https://github.com/microsoft/winget-pkgs/issues/80626
https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/r/rambox.ramboxce.json
Thanks!

**Comment by vedantmgoyal9** [comment]
For every GitHub package, you can request the package maintainer to use: https://github.com/marketplace/actions/winget-releaser

**Comment by ppvnf** [comment]
I've opened support ticket [#6975](https://support.rambox.app/support/tickets/6975) asking about that

**Comment by ppvnf** [comment]
Answer was: "The package in WinGet is not maintained by us, and we don't have plans to do it for now."

Should this be closed or there's a plan B?

**Comment by vedantmgoyal9** [comment]
It will be added here. I'm currently struggling with Docker (the world's worst product I've seen in my life, doesn't have any error handling, and the error messages aren't useful either). I don't get how it became so famous, its error messages are just crap.

**Comment by ppvnf** [comment]
💪I wish MS would give you free access to Azure, as you are providing Winget a functionality ahead of time
