### ISSUE TITLE
[New Package]: KDE.Kdenlive

### ISSUE THREAD

**Issue by ppvnf** [vedantmgoyal9/winget-pkgs-automation#928]
### List the PackageIdentifier of the package to be added to automation

KDE.Kdenlive

### Details about the application

https://github.com/microsoft/winget-pkgs/pull/79637
https://github.com/microsoft/winget-pkgs/pull/73233
https://github.com/KDE/kdenlive/releases/tag/v22.08.2 (source code)
https://kdenlive.org/en/download/

Current version 22.08.1. Available 22.08.2

**Comment by vedantmgoyal9** [comment]
Since they don't publish EXEs in GitHub releases, I don't think the action can be used here. A good way to know if the action can be used is that the installer URL should follow this structure: `https://github.com/<owner>/<repo>/releases/download/<tag>/<filename>`.

Also, I'm creating a new issue and will post PackageIdentifier and issue URL there. Separate issues for each package will be difficult to track.

**Comment by ppvnf** [comment]
Then, shouldn't this be left open, since they don't publish .EXEs on GitHub?
Or do you also plan to create another issue for packages that are unable to use winget-releaser?

**Comment by vedantmgoyal9** [comment]
No, they use their own Jenkins CI, and it's the maintainers' choice. It is not necessary that a package which hosts it source-code on GitHub does necessarily use all features of GitHub.

**Comment by ppvnf** [comment]
> No, they use their own Jenkins CI, and it's the maintainers' choice. It is not necessary that a package which hosts it source-code on GitHub does necessarily use all features of GitHub.

Ok. Do you think it's worth it opening an issue [here](https://invent.kde.org/multimedia/kdenlive/-/issues)?

**Comment by vedantmgoyal9** [comment]
Nope, since a GitHub Action can only be utilized by GitHub worklfows only.

**Comment by ppvnf** [comment]
Shouldn't version 22.08.2 have been pushed already?

**Comment by ppvnf** [comment]
There are two 22.08.2 versions. I think that for Kdenlive it's better to use [the one from https://kdenlive.org/en/download/](https://download.kde.org/stable/kdenlive/22.08/windows/kdenlive-22.08.2.exe) instead of [this one](https://binary-factory.kde.org/job/Kdenlive_Stable_mingw64/)

**Comment by vedantmgoyal9** [comment]
The latter one, other packages also use binary-factory links.

**Comment by ppvnf** [comment]
there are 3 issues about KDE software:
https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/928
https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/934
https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/185
