### ISSUE TITLE
[New Package]: gerardog.gsudo

### ISSUE THREAD

**Issue by ppvnf** [vedantmgoyal9/winget-pkgs-automation#929]
### List the PackageIdentifier of the package to be added to automation

gerardog.gsudo

### Details about the application

https://github.com/gerardog/gsudo
I know you are already automating it, but if you wish I can ask him to use winget-releaser

**Comment by vedantmgoyal9** [comment]
I'm creating a new issue and will post PackageIdentifier and issue URL there. Separate issues for each package will be difficult to track.
