### ISSUE TITLE
[New Package]: t1m0thyj.WinDynamicDesktop

### ISSUE THREAD

**Issue by ppvnf** [vedantmgoyal9/winget-pkgs-automation#930]
### List the PackageIdentifier of the package to be added to automation

t1m0thyj.WinDynamicDesktop

### Details about the application

I can also try asking him to use winget-releaser, even though it's already automated
https://github.com/t1m0thyj/WinDynamicDesktop

**Comment by vedantmgoyal9** [comment]
I'm creating a new issue and will post PackageIdentifier and issue URL there. Separate issues for each package will be difficult to track.
