### ISSUE TITLE
[Bug]: KDE.Okular not being updated on microsoft/winget-pkgs

### ISSUE THREAD

**Issue by rodrigopedra** [vedantmgoyal9/winget-pkgs-automation#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Project Name

WinGet Automation

### What happened?

I was filling a a package request to add KDE.Okular when I saw it is already listed on the packages this repo automates.

The current KDE.Okular version on winget is outdated, and was not provided by this repo automation bot.

Moreover the current link yields a 403 when installing KDE.Okular through winget.

If there is anything I can do to help on this, let me know.

**Comment by ppvnf** [comment]
[Here ](https://okular.kde.org/download/) they recommend to use the MS Store version and https://binary-factory.kde.org/job/Okular_Release_win64/ as an alternative. I imagine the same applies to other KDE products such as Kate

**Comment by ppvnf** [comment]
I am unsure which one should be used:

https://download.kde.org/stable/release-service/22.08.1/windows/okular-22.08.1-windows-msvc2019_64-cl.exe

or 

https://binary-factory.kde.org/job/Okular_Release_win64/lastSuccessfulBuild/artifact/okular-22.08.2-1176-windows-msvc2019_64-cl.exe

**Comment by vedantmgoyal9** [comment]
The latter one. Other KDE packages in WinGet also use binary-factory links, hence this should too.

**Comment by ppvnf** [comment]
I've confirmed that KDE.Kate current download link is also broken

**Comment by vedantmgoyal9** [comment]
* PR is already open for that: https://github.com/microsoft/winget-pkgs/pull/85182

**Comment by rodrigopedra** [comment]
Kate's PR was already merged, and I can confirm it is available through `winget`.

If I can help with Okular, please let me know and please provide any first steps I could follow.

Thanks in advance.

**Comment by ppvnf** [comment]
Thanks! How long does it take for the auto-update to take place?

**Comment by vedantmgoyal9** [comment]
It takes 1 hour normally, but PRs aren't created due to https://github.com/actions/runner-images/issues/6446.
