### ISSUE TITLE
profile doesn't load

### ISSUE THREAD

**Issue by dpprdan** [vedantmgoyal9/winget-pkgs-automation#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Just as a heads-up: Your [profile page](https://github.com/vedantmgoyal2009) takes too long to display since a few days. I always get
![image](https://user-images.githubusercontent.com/1423562/197521481-7ffd4898-caa4-4ed7-b5c5-4caf55498204.png)

I think it's the GH stats in your [README](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/README.md).

**Comment by vedantmgoyal9** [comment]
It's due to a bug in GitHub, about which I'm lazy to open a support ticket to GitHub 😅

**Comment by vedantmgoyal9** [comment]
I've set my profile activity to private, which fixes the issue(?)

**Comment by dpprdan** [comment]
Yes, it does! 🎉
