### ISSUE TITLE
[Bug]: pgAdmin manifest update did not land in winget-pkgs repo

### ISSUE THREAD

**Issue by dpprdan** [vedantmgoyal9/winget-pkgs-automation#950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The latest pgAdmin release ([v6.15](https://github.com/pgadmin-org/pgadmin4/releases/tag/REL-6_15)) did not make it to the winget-pkgs repo, yet. 
IIUC the latest pgAdmin release was [processed by wpa](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/9ea630a48e8eb5abb6483575649dc42bef195edc/winget-pkgs-automation/packages/p/postgresql.pgadmin.json#L15) more than 3 days ago, but did not result in a [winget-pkgs PR](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+pgadmin+is%3Aclosed) (yet?).

**Comment by vedantmgoyal9** [comment]
* The PRs are not created due to https://github.com/actions/runner-images/issues/6446.

Once it is resolved, I'll revert the commits and re-run the automatioin again.
