### ISSUE TITLE
[Bug]: Okular not available on WInget

### ISSUE THREAD

**Issue by ppvnf** [vedantmgoyal9/winget-pkgs-automation#955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/microsoft/winget-pkgs/pull/86636/commits/53c3867319861fea2680a09360b6ee87932c63a9

Even though it's merged `winget search` won't find the updated package

**Comment by vedantmgoyal9** [comment]
* https://github.com/microsoft/winget-pkgs/issues/86160
